id: P444D34B5
initial_creation_type: ocr
source_metadata:
  volumes:
    09ebe16be0dd4756bc97c850e02fbbb4:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་སྒྲུབ་ཐབས།
      total_pages: 1648
      volume_number: 40
